services:
  - type: web
    name: pdf-api
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAPIDAPI_PROXY_SECRET
        sync: false
      - key: PUPPETEER_ARGS
        value: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage
